# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privrew < Formula
  desc "It is a CLI tool that makes it easier to deploy private repositories."
  homepage "https://github.com/ghdwlsgur/privrew"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.3/privrew_0.0.3_Darwin_arm64.tar.gz"
      sha256 "40691f53fb77908d62c381e6ed5d8a4c7bb0e2647988c1c445ee8ad1cd49fd69"

      def install
        bin.install "privrew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.3/privrew_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "0e959e9940759d2dd503b2dc75d088639a57f1eb15a7ac144cc1f0e2d399cfaf"

      def install
        bin.install "privrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.3/privrew_0.0.3_Linux_arm64.tar.gz"
      sha256 "a2d83cbf3f8928a2739db6f8bc2a8f28999c7f07fe19a4b823134e1cb4c8bfd0"

      def install
        bin.install "privrew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.3/privrew_0.0.3_Linux_x86_64.tar.gz"
      sha256 "e8d2de8808bbf0759440749bdfc1b4459954b60befaf79f15ff3672bfaa15bac"

      def install
        bin.install "privrew"
      end
    end
  end
end
