# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privrew < Formula
  desc "It is a CLI tool that makes it easier to deploy private repositories."
  homepage "https://github.com/ghdwlsgur/privrew"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.2/privrew_0.0.2_Darwin_arm64.tar.gz"
      sha256 "bfbb1cf9fe894d8a34060e5573f977497349ebb4cbb3bc81cbdf25e021f56a3d"

      def install
        bin.install "privrew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.2/privrew_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "caf5c5262b1e7187d30770f370ce8377ab69a3404ddfb214abbfbf0d83f93cba"

      def install
        bin.install "privrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.2/privrew_0.0.2_Linux_arm64.tar.gz"
      sha256 "70fe07aad8e4cb2ebf3289215580dda74bad533a3a91e78137a58b8bf0164bc7"

      def install
        bin.install "privrew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.2/privrew_0.0.2_Linux_x86_64.tar.gz"
      sha256 "1f774bb7d0a2f1b122639519ffa52fe2c61aec70e04f5aee744a6576e9143a15"

      def install
        bin.install "privrew"
      end
    end
  end
end
