# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privrew < Formula
  desc "It is a CLI tool that makes it easier to deploy private repositories."
  homepage "https://github.com/ghdwlsgur/privrew"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.1/privrew_0.0.1_Darwin_arm64.tar.gz"
      sha256 "8a4f1ffaef747dc570b5d3bcca3759c9b7219808dd6f5d84194f989d5c4aaf5b"

      def install
        bin.install "privrew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.1/privrew_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "5da0f39b2f3aa931b57520b99d2a18ecdf56a7cd80df5ee96fbe615c23ebd9bf"

      def install
        bin.install "privrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.1/privrew_0.0.1_Linux_arm64.tar.gz"
      sha256 "2df9a48d17b7f3c784790e8c00442d703d04e287def6c85bc460a270e2ba5326"

      def install
        bin.install "privrew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/privrew/releases/download/v0.0.1/privrew_0.0.1_Linux_x86_64.tar.gz"
      sha256 "c9cb5142d623da19715c749196e95c37dc526ff1ea4a77925ba6589196c8903b"

      def install
        bin.install "privrew"
      end
    end
  end
end
